### ISSUE TITLE
can u add docker, docker compose, http, webdav and ftp support?

### ISSUE THREAD

**Issue by aniel300** [RutexOrg/DiscordFileStorage#5]
can u add docker, docker compose, http, webdav and ftp support?

**Comment by rutexd** [comment]
Hello.

Webdav is already here or did I misunderstood you?

I planned to add ftp and http support too, so probably yes. However I cannot say exactly when, since it will require time and at the moment I do not have much time for this. 

Docker wouldn't be a problem too. 

Will do it in a week or two.

**Comment by aniel300** [comment]
sounds good bud. idk programming at the moment otherwise i would help you. regardless take ur time and keep me updated, TIA.

**Comment by rutexd** [comment]
I added simple http ui and docker files. Not gonna to add ftp for now, since it will require some maintenance and refactoring. dav server now on ``/dav`` endpoint, ui on ``/``.

**Comment by aniel300** [comment]
is there a docker image?

**Comment by rutexd** [comment]
No. 
You can easily build it on your own local machine. Dockerfile should do everything.

**Comment by aniel300** [comment]
i deploy all my containers using an image hosted on the docker hub or gh. idk how to build this image. can u publish the image to the docker hub or gh?

**Comment by rutexd** [comment]
I rarely use Docker (almost never) for my own needs and have not so much knowledge of the Docker infrastructure. I can try to upload an image however I am not aware of the nuances and proper practices with Docker. 

You can build the image very easy local. Just clone the repo, naviate to a cloned directory in your shell and run ``docker build -t app .``. Where ``app`` your tag you want it to have.
Then you can run it with something like ``docker run -p 3000:3000 app``. Dont forget to provide token and id as it described in readme.
If your images running local only and you dont plan to upload somewhere, i guess, you can just create .env file, adapt Dockerfile to copy it instead .env.example and build image with it. Or if you using docker gui you can provide same env. variables from a gui runner to a container.

**Comment by aniel300** [comment]
i use docker and docker compose to deploy my containers. usually the project/ dev has a docker compose sample where i adapt it to my set up and all is good. this project not having an image on the docker hub or gh it makes it hard for me to deploy, hope u understand and do please give a try uploading the docker image to the docker hub or gh, TIA.

**Comment by rutexd** [comment]
Should be online. ``rutexd/dicloud``.

**Comment by aniel300** [comment]
perfect i will give it a try and report back, many thanks 🙏

**Comment by aniel300** [comment]
am getting these errors...where can define the token, etc in the docker compose file or at the os fs level?

```
yarn run v1.22.19
$ node --no-warnings out/bootloader.js
Required env variable TOKEN is not set: Please set the TOKEN to your bot token. Please set it in .env file or in your system environment variables.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
yarn run v1.22.19
$ node --no-warnings out/bootloader.js
Required env variable TOKEN is not set: Please set the TOKEN to your bot token. Please set it in .env file or in your system environment variables.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
yarn run v1.22.19
$ node --no-warnings out/bootloader.js
Required env variable TOKEN is not set: Please set the TOKEN to your bot token. Please set it in .env file or in your system environment variables.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
yarn run v1.22.19
$ node --no-warnings out/bootloader.js
Required env variable TOKEN is not set: Please set the TOKEN to your bot token. Please set it in .env file or in your system environment variables.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
yarn run v1.22.19
$ node --no-warnings out/bootloader.js
Required env variable TOKEN is not set: Please set the TOKEN to your bot token. Please set it in .env file or in your system environment variables.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
yarn run v1.22.19
$ node --no-warnings out/bootloader.js
Required env variable TOKEN is not set: Please set the TOKEN to your bot token. Please set it in .env file or in your system environment variables.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
yarn run v1.22.19
$ node --no-warnings out/bootloader.js
Required env variable TOKEN is not set: Please set the TOKEN to your bot token. Please set it in .env file or in your system environment variables.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
yarn run v1.22.19
$ node --no-warnings out/bootloader.js
Required env variable TOKEN is not set: Please set the TOKEN to your bot token. Please set it in .env file or in your system environment variables.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
yarn run v1.22.19
$ node --no-warnings out/bootloader.js
Required env variable TOKEN is not set: Please set the TOKEN to your bot token. Please set it in .env file or in your system environment variables.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
yarn run v1.22.19
$ node --no-warnings out/bootloader.js
Required env variable TOKEN is not set: Please set the TOKEN to your bot token. Please set it in .env file or in your system environment variables.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
yarn run v1.22.19
$ node --no-warnings out/bootloader.js
Required env variable TOKEN is not set: Please set the TOKEN to your bot token. Please set it in .env file or in your system environment variables.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
yarn run v1.22.19
$ node --no-warnings out/bootloader.js
Required env variable TOKEN is not set: Please set the TOKEN to your bot token. Please set it in .env file or in your system environment variables.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by rutexd** [comment]
The app reads environment variables. It plays no matter how do you define environment variables. You can define variables via docker somehow, you can define variables via .env file in the root of the project: app will read the file automatically and load everything up.

**Comment by aniel300** [comment]
can i define it on the docker compose file? for example

```
  dicloud:
    container_name: dicloud
    image: rutexd/dicloud
    ports:
      - "3000:3000"
    volumes:
      - /docker/dicloud/certs:/app/certs
    environment:
      - NODE_ENV=production
      #Token obtained in bot control panel
      - TOKEN="TOKEN_HERE" 
      #Guild (server) id where your bot located. For example: 123456789012345
      - GUILD_ID="GUILD_ID_HERE" 
    restart: unless-stopped
    ```

**Comment by rutexd** [comment]
I guess, this can work. Havent tested this way.

**Comment by aniel300** [comment]
i tried but am getting those error now
```
Env variable FILES_CHANNEL is not set: Please set the FILES_CHANNEL to your files channel name. Using default value: files
Env variable META_CHANNEL is not set: Please set the META_CHANNEL to your meta channel name. Using default value: meta
Env variable PORT is not set: Please set the PORT to your webdav server port. Using default value: 3000
Env variable ENABLE_HTTPS is not set: Please set the ENABLE_HTTPS to true or false to enable https. Using default value: false
Env variable AUTH is not set: Please set the AUTH to true or false to enable auth. Using default value: false
Env variable USERS is not set: Please set the USERS to your users in format username:password,username:password. Using default value: N/A
Env variable ENCRYPT is not set: Please set the ENCRYPT to true or false to enable encryption. Using default value: false
Env variable ENCRYPT_PASS is not set: Please set the ENCRYPT_PASSWORD to your encryption password. Using default value: N/A
Env variable SAVE_TIMEOUT is not set: Please set the SAVE_TIMEOUT to your save timeout in ms. Using default value: 2000
Env variable SAVE_TO_DISK is not set: Please set the SAVE_TO_DISK to true or false to enable saving to disk. Using default value: false
NodeJS version: v20.9.0
Starting DICloud...
Logging in...
Trace: Error [TokenInvalid]: An invalid token was provided.
    at WebSocketManager.connect (/app/node_modules/discord.js/src/client/websocket/WebSocketManager.js:136:26)
    at Client.login (/app/node_modules/discord.js/src/client/Client.js:228:21)
    at DICloudApp.login (/app/out/src/DICloudApp.js:105:34)
    at boot (/app/out/bootloader.js:75:15)
    at envBoot (/app/out/bootloader.js:300:18)
    at Object.<anonymous> (/app/out/bootloader.js:325:5)
    at Module._compile (node:internal/modules/cjs/loader:1241:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1295:10)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Module._load (node:internal/modules/cjs/loader:938:12) {
  code: 'TokenInvalid'
}
    at process.<anonymous> (/app/out/bootloader.js:323:17)
    at process.emit (node:events:514:28)
    at emit (node:internal/process/promises:150:20)
    at processPromiseRejections (node:internal/process/promises:284:27)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:32)
Done in 1.19s.
yarn run v1.22.19
$ node --no-warnings out/bootloader.js
Env variable FILES_CHANNEL is not set: Please set the FILES_CHANNEL to your files channel name. Using default value: files
Env variable META_CHANNEL is not set: Please set the META_CHANNEL to your meta channel name. Using default value: meta
Env variable PORT is not set: Please set the PORT to your webdav server port. Using default value: 3000
Env variable ENABLE_HTTPS is not set: Please set the ENABLE_HTTPS to true or false to enable https. Using default value: false
Env variable AUTH is not set: Please set the AUTH to true or false to enable auth. Using default value: false
Env variable USERS is not set: Please set the USERS to your users in format username:password,username:password. Using default value: N/A
Env variable ENCRYPT is not set: Please set the ENCRYPT to true or false to enable encryption. Using default value: false
Env variable ENCRYPT_PASS is not set: Please set the ENCRYPT_PASSWORD to your encryption password. Using default value: N/A
Env variable SAVE_TIMEOUT is not set: Please set the SAVE_TIMEOUT to your save timeout in ms. Using default value: 2000
Env variable SAVE_TO_DISK is not set: Please set the SAVE_TO_DISK to true or false to enable saving to disk. Using default value: false
NodeJS version: v20.9.0
Starting DICloud...
Logging in...
Trace: Error [TokenInvalid]: An invalid token was provided.
    at WebSocketManager.connect (/app/node_modules/discord.js/src/client/websocket/WebSocketManager.js:136:26)
    at Client.login (/app/node_modules/discord.js/src/client/Client.js:228:21)
    at DICloudApp.login (/app/out/src/DICloudApp.js:105:34)
    at boot (/app/out/bootloader.js:75:15)
    at envBoot (/app/out/bootloader.js:300:18)
    at Object.<anonymous> (/app/out/bootloader.js:325:5)
    at Module._compile (node:internal/modules/cjs/loader:1241:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1295:10)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Module._load (node:internal/modules/cjs/loader:938:12) {
  code: 'TokenInvalid'
}
    at process.<anonymous> (/app/out/bootloader.js:323:17)
    at process.emit (node:events:514:28)
    at emit (node:internal/process/promises:150:20)
    at processPromiseRejections (node:internal/process/promises:284:27)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:32)
Done in 1.36s.
yarn run v1.22.19
$ node --no-warnings out/bootloader.js
Env variable FILES_CHANNEL is not set: Please set the FILES_CHANNEL to your files channel name. Using default value: files
Env variable META_CHANNEL is not set: Please set the META_CHANNEL to your meta channel name. Using default value: meta
Env variable PORT is not set: Please set the PORT to your webdav server port. Using default value: 3000
Env variable ENABLE_HTTPS is not set: Please set the ENABLE_HTTPS to true or false to enable https. Using default value: false
Env variable AUTH is not set: Please set the AUTH to true or false to enable auth. Using default value: false
Env variable USERS is not set: Please set the USERS to your users in format username:password,username:password. Using default value: N/A
Env variable ENCRYPT is not set: Please set the ENCRYPT to true or false to enable encryption. Using default value: false
Env variable ENCRYPT_PASS is not set: Please set the ENCRYPT_PASSWORD to your encryption password. Using default value: N/A
Env variable SAVE_TIMEOUT is not set: Please set the SAVE_TIMEOUT to your save timeout in ms. Using default value: 2000
Env variable SAVE_TO_DISK is not set: Please set the SAVE_TO_DISK to true or false to enable saving to disk. Using default value: false
NodeJS version: v20.9.0
Starting DICloud...
Logging in...
Trace: Error [TokenInvalid]: An invalid token was provided.
    at WebSocketManager.connect (/app/node_modules/discord.js/src/client/websocket/WebSocketManager.js:136:26)
    at Client.login (/app/node_modules/discord.js/src/client/Client.js:228:21)
    at DICloudApp.login (/app/out/src/DICloudApp.js:105:34)
    at boot (/app/out/bootloader.js:75:15)
    at envBoot (/app/out/bootloader.js:300:18)
    at Object.<anonymous> (/app/out/bootloader.js:325:5)
    at Module._compile (node:internal/modules/cjs/loader:1241:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1295:10)
    at Module.load (node:internal/modules/cjs/loader:1091:32)
    at Module._load (node:internal/modules/cjs/loader:938:12) {
  code: 'TokenInvalid'
}
    at process.<anonymous> (/app/out/bootloader.js:323:17)
    at process.emit (node:events:514:28)
    at emit (node:internal/process/promises:150:20)
    at processPromiseRejections (node:internal/process/promises:284:27)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:32)
Done in 1.17s.
```

**Comment by rutexd** [comment]
You sure you provided the correct token? No spaces and no any other chars etc?

**Comment by aniel300** [comment]
yep i followed this to get the two peace of info
![image](https://github.com/user-attachments/assets/2a82b93a-0ffc-4c48-99f4-d283a863c05a)

**Comment by rutexd** [comment]
just tested it. It works for me... I can't reproduce your error.

The instructions from readme have changed a bit in 2.5 years, but if you gave administrator rights and put scope=bot, everything should work.... Most likely you made a mistake somewhere - wrong copying, extra space, extra new line, etc. The error is happening at login step, not even at channel management... 
In other error cases the error text would probably be different.

**Comment by aniel300** [comment]
any update on this? i did everything correct and i copy and pasted everything so there shouldn't have been any error. i can give u my info in private if needed

**Comment by rutexd** [comment]
How do you obtain the token? Via reset token and then just copy?

**Comment by aniel300** [comment]
i followed this https://github.com/RutexOrg/DiscordFileStorage#bot-creation and here is screenshot of bot that was added to the discord server
![Discord_6DNzsLKrsW](https://github.com/user-attachments/assets/b0bbec8e-a6b8-472a-b404-865f630b7c42)

**Comment by rutexd** [comment]
Sorry, it's hard to tell me what's wrong since I'm not using docker everyday. Feel free to reopen if there other problems.

**Comment by aniel300** [comment]
is to bad this didn't work as i was looking forward to make it work. if u need some insensitive/ want me to help debug this please let me know and i can try to make it work.
